name: My Workflow

on:
  push:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script with API Keys
        run: |
          python youtube_video_download_and_upload_to_drive.py
#
#          chmod 777  /home/runner/work/youtube_vedio_editor_action/youtube_vedio_editor_action/downloaded_videos/

      - name: Set output
        if: always()
        id: results
        run: echo "artifactPath=voices/" >> $GITHUB_OUTPUT

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-try
          path: voices
